### PR TITLE
feat: add a lookahead to the grammar to make sure a chords line is only chords

### PR DESCRIPTION
**Pull request by isaiahdahl**
fixes: #510 

This gets is part of the way there for the problem of ambiguity for a lyrics line being recognized as chords.

It's a look-ahead when trying to match a chords line to check if there are word chars. 
It handles a lot more scenarios and even passes the complicated Kingdom Chart test (which I now changed from 'xit' to "it")

It still will have the problem of parsing a lyric line where each word in the lyric line starts with a letter A-G

I added a "xit" test showing this.

CleanShot 2023-06-21 at 08 36 57

I think the only way to fix that is to make it so a chord suffix can't be anything. That's how we did it for the syntax highlighting lezer grammar anyway.

### CODE REVIEW

**Comment by carloseustaquio** [comment]
Hi @isaiahdahl @martijnversluis! I'm new to the ChordSheetJS community, but I'm facing exactly the same issue this PR is fixing. Are there any plans for releasing this? Thank you in advance! This is an awesome project

**Comment by martijnversluis** [comment]
@isaiahdahl I got it working using a few tricks:

- there was not really a way to come up with a grammar pattern, so the grammar just literally lists each suffix
- I removed chord suffixes containing a space, as that breaks chord sheet parsing. I wonder if that's a problem. We could also only remove those suffixes for generating the grammar.
- I had to add some suffixes that were used in tests but were not in the suffixes file. I'm wondering if more could be missing. If we merge this both `ChordsOverWordParser` and `Chord.parse` depend on this grammar.

What do you think?

**Comment by isaiahdahl** [comment]
@martijnversluis

Yea I thought it'd be tough to come up with that grammar, we did something for our [syntax highlighter grammar](https://github.com/bettermusic/studio/blob/master/packages/codemirror-lang-chordpro/src/tokens.ts)  You can take a look at the readSuffix related functions. Though to be honest I'm not sure it's entirely a bad thing to just maintain a list of suffixs like you have implemented, how many can there be. Could even think about adding something to a configuration that allows people to initialize additional suffixes if they wanted special cases, and otherwise people just make PR's to update the list. (not sure if that would actually work with the grammar being compiled) 

I'm totally ok with chord suffxes not being allowed to contain a space. In my opinion I think that's just an error in that suffix file that we have and it doesn't generate errors for us. 

Again with missing ones, I think we just add missing ones till it's complete, you only have to add missing ones once haha! The reality is, there aren't an infinite amount of suffix' but the list of suffix's approach gives the ability to be very robust in what is supported as well as handle obscurities.

**Comment by martijnversluis** [comment]
Ok great @isaiahdahl, thanks for your reply. Gonna merge this :shipit:

**Pull request merged**
