### PR TITLE
Fix yarn install issues

### PR DESCRIPTION
**Pull request by martijnversluis**

### CODE REVIEW

**Comment by isaiahdahl** [comment]
@martijnversluis  I was able to build this one!

**Comment by isaiahdahl** [comment]
I also enabled corepack which i wasn't using before so maybe that's helped too.

It's interesting that the error I was seeing is the same error that's in the 22.6 error here, but I was seeing it in all node versions.

**Comment by martijnversluis** [comment]
I merged some upstream changes to try and fix the Verify step. However, that contains a major ESLint update including ESLint config changes. 

I'll try and fix the issues for master, but I'm afraid it will also require some effort to please ESLint in the soft line break PR....

**Comment by isaiahdahl** [comment]
Ok well now that I can build I should be able to resolve them and get the basic test back to passing. I guess just bring this into master and then I can rebase the PR and fix them.

**Comment by isaiahdahl** [comment]
Oh I see, master here already has the start of the pdf_formatter so that's always going to fail... and is sorta pointless to fix the eslint because it's changed so much in the other PR.

Maybe just merge this in? and then we can rebase the other and I can fix all of them there?

**Comment by isaiahdahl** [comment]
OR.... I just cherry pick that yarn.lock fix into the soft line breaks branch and push that there. Fix the test, and get the green light. 

Then we do another PR to update from upstream and fix the lint then

**Comment by isaiahdahl** [comment]
well looks like it wasn't that hard..... haha

**Pull request merged**
